# Use an official Python runtime as a parent image
FROM --platform=linux/amd64 python:3.12-slim-bookworm


# Fix the LegacyKeyValueFormat warnings
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# 1. Move the requirements file from your Mac to the container
COPY requirements.txt .

# 2. Now you can install them
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# 3. Copy the rest of your application code
COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8005"]
